spring.application.name=nightbite-backend

# 1. Cau hinh ket noi MySQL Local
# Tham so createDatabaseIfNotExist=true giup tu dong tao DB 'nightbite_db' neu may ban chua co
spring.datasource.url=jdbc:mysql://localhost:3306/nightbite_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dien Username va Password cua MySQL Workbench / MySQL Server tren may ban vao day
spring.datasource.username=root
spring.datasource.password=12345

# 2. Cau hinh Hibernate / JPA (Co che Code First)
# 'update' giup tu dong tao bang tu Java Entity va cap nhat thay doi ma khong lam mat du lieu cu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Show log cac cau lenh SQL ra Console de Nha va Khoi tien debug, kiem tra khi chay API
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true