import { Product, Notification, UserProfile } from './types';

export const CATEGORIES = [
  { id: 'all', label: 'Tất cả', icon: 'Sparkles' },
  { id: 'cake', label: 'Bánh Gato', icon: 'Cake' },
  { id: 'pastry', label: 'Bánh Mì', icon: 'Croissant' },
  { id: 'cookie', label: 'Cookie & Donut', icon: 'Cookie' },
  { id: 'drinks', label: 'Thức Uống', icon: 'Coffee' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'sb_01',
    name: 'Bánh Kem Dâu Tây Savi',
    price: 65000,
    originalPrice: 75000,
    description: 'Bánh gato cốt dâu tây mềm ẩm ngọt mát kết hợp lớp kem sữa tươi Hokkaido thanh nhẹ và những lát dâu tươi căng mọng.',
    category: 'cake',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    salesCount: 230,
    sizes: ['S (Slice)', 'M (Ổ nhỏ)', 'L (Ổ lớn)'],
    sweetnessLevels: ['50% Ngọt', '70% Ngọt', '100% Ngọt Chuẩn'],
    hotDeals: true,
  },
  {
    id: 'sb_02',
    name: 'Tiramisu Klasik Ý',
    price: 55000,
    description: 'Bánh Tiramisu truyền thống Ý với cốt bánh thấm đượm espresso đậm đà cùng rượu rum hảo hạng xen kẽ phô mai Mascarpone.',
    category: 'cake',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&q=80&w=400',
    rating: 4.8,
    salesCount: 185,
    sizes: ['S (Slice)', 'M (Hũ gỗ)'],
    sweetnessLevels: ['70% Ít ngọt', '100% Ngọt Chuẩn'],
    hotDeals: true,
  },
  {
    id: 'sb_03',
    name: 'Bánh Croissant Bơ Pháp',
    price: 35000,
    originalPrice: 45000,
    description: 'Bánh mì sừng bò bơ Pháp ngàn lớp giòn rụm bên ngoài, xốp mềm mọng ẩm bên trong, dậy hương bơ cao cấp thơm lừng.',
    category: 'pastry',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=400',
    rating: 4.7,
    salesCount: 310,
    sizes: ['Standard Size'],
    sweetnessLevels: ['Không ngọt', 'Ngọt nhẹ bơ'],
    hotDeals: true,
  },
  {
    id: 'sb_04',
    name: 'Mousse Matcha Sữa Ong Chúa',
    price: 59000,
    description: 'Được làm từ bột trà xanh Uji tinh khiết Nhật Bản kết hợp mật ong rừng tạo nên vị đắng tinh sảo đan xen ngọt bùi.',
    category: 'cake',
    image: 'https://images.unsplash.com/photo-1536680465769-2365207b035e?auto=format&fit=crop&q=80&w=400',
    rating: 4.8,
    salesCount: 145,
    sizes: ['Slice Standard'],
    sweetnessLevels: ['30% Đắng nhẹ', '50% Vừa vị', '100% Ngọt Chuẩn'],
    hotDeals: false,
  },
  {
    id: 'sb_05',
    name: 'Donut Chocolate Giòn Hạnh Nhân',
    price: 29000,
    description: 'Bánh donut chiên phồng phủ lớp chocolate đắng 65% thượng hạng cùng hạnh nhân rang giòn thơm lừng.',
    category: 'cookie',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=400',
    rating: 4.6,
    salesCount: 220,
    sizes: ['1 Chiếc', 'Hộp 4 chiếc (Khuyến mãi)'],
    sweetnessLevels: ['70% Ngọt vừa', '100% Đậm đặc'],
    hotDeals: false,
  },
  {
    id: 'sb_06',
    name: 'Cookie Macadamia Khổng Lồ',
    price: 32000,
    description: 'Bánh quy bơ mềm nướng kiểu Mỹ ngập bụi hạt macadamia hảo hạng và các viên socola đen béo ngậy.',
    category: 'cookie',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    salesCount: 175,
    sizes: ['1 Chiếc lớn', 'Cặp 2 chiếc'],
    hotDeals: false,
  },
  {
    id: 'sb_07',
    name: 'Cupcake Việt Quất Kem Kem',
    price: 38000,
    description: 'Cupcake vani cốt xốp bông với lòng bánh chứa đầy mứt quả blueberry tươi, bọc trên là kem whipping mềm mượt.',
    category: 'cake',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=400',
    rating: 4.7,
    salesCount: 120,
    sizes: ['Standard'],
    sweetnessLevels: ['50% Ít ngọt', '100% Chuẩn vị'],
    hotDeals: false,
  },
  {
    id: 'sb_08',
    name: 'Bánh Mì Đan Mạch Việt Quất Đỏ',
    price: 42000,
    description: 'Bánh nướng Danish pastry xốp giòn phủ kem custard ngọt dịu và dâu tây dại khô cùng quả nam việt quất chua nhẹ.',
    category: 'pastry',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400',
    rating: 4.8,
    salesCount: 190,
    sizes: ['Standard'],
    hotDeals: false,
  },
  {
    id: 'sb_09',
    name: 'Cà Phê Muối Savi Đặc Biệt',
    price: 45000,
    description: 'Cà phê Espresso pha lạnh đậm vị, bên trên là lớp bọt kem muối biển mặn ngọt độc quyền siêu ghiền.',
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    salesCount: 420,
    sizes: ['Size M', 'Size L'],
    sweetnessLevels: ['70% Ít ngọt', '100% Ngọt béo chuẩn'],
    hotDeals: true,
  },
  {
    id: 'sb_10',
    name: 'Trà Đào Cam Sả Savi',
    price: 39000,
    description: 'Trà đào ngọt ngào tươi mát hòa quyện cùng cốt cam sả sảng khoái và 3 lát đào giòn ngọt chất lượng.',
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    rating: 4.7,
    salesCount: 290,
    sizes: ['Size M', 'Size L'],
    sweetnessLevels: ['50% Ngọt dịu', '100% Đủ trà đậm vị'],
    hotDeals: false,
  }
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'not_01',
    title: '🎁 Quà Tặng Lần Đầu Đến SaviBite!',
    content: 'Tặng bạn mã ưu đãi giảm ngay 15% cho đơn hàng bánh kem ngọt đầu tiên. Nhập mã: SAVIBITE15 tại giỏ hàng nhé!',
    time: 'Vừa xong',
    read: false,
    type: 'promo',
  },
  {
    id: 'not_02',
    title: '🍰 Siêu ƯU ĐÃI: Combo Trà Ô Long & Sừng Bò',
    content: 'Thưởng thức bữa xế cực chill chỉ với 59.000đ khi gọi combo bánh Croissant Pháp và Trà Ô Long Kem Phô Mai thượng hạng.',
    time: '2 giờ trước',
    read: false,
    type: 'promo',
  },
  {
    id: 'not_03',
    title: '🎉 Nâng hạng thành viên thành công!',
    content: 'Chúc mừng bạn đã được nâng cấp lên hạng thành viên VÀNG (Gold Member) với cực nhiều ưu đãi tích lũy SaviPoints tốt hơn.',
    time: '1 ngày trước',
    read: true,
    type: 'system',
  },
];

export const INITIAL_USER: UserProfile = {
  name: "Duy Nguyễn Zalo",
  phone: "0987 *** 321",
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=200",
  tier: "Gold",
  points: 1520,
  savedVouchers: ['SAVIBITE15', 'FREESHIP', 'MUA1TANG1']
};

export const MOCK_REVIEWS = [
  {
    id: 'rev_01',
    userName: 'Lan Hương',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100',
    rating: 5,
    comment: 'Bánh dâu tây ngon tuyệt đỉnh! Kem thơm béo mà không ngấy, dâu siêu tươi luôn á. Đặt Zalo giao hàng nhanh cực kì.',
    date: '10/06/2026',
  },
  {
    id: 'rev_02',
    userName: 'Minh Quân',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100',
    rating: 5,
    comment: 'Cà phê muối uống ngền lắm cơ, bọt kem mặn mặn béo ngậy phối với Croissant bơ giòn chuẩn không chỉnh.',
    date: '18/06/2026',
  }
];

export const PROMO_VOUCHERS = [
  { code: 'SAVIBITE15', description: 'Giảm 15% cho đơn hàng bánh Gato/Cake', discountPercent: 15, minOrder: 50000 },
  { code: 'FREESHIP', description: 'Miễn phí vận chuyển toàn quốc (tối đa 25k)', discountValue: 25000, minOrder: 100000 },
  { code: 'SAVI50K', description: 'Giảm thẳng 50.000đ cho hóa đơn từ 200k', discountValue: 50000, minOrder: 200000 }
];

export const MYSTERY_BOXES = [
  {
    id: 'mb_35',
    name: 'Mystery Box',
    badge: 'Standard Box',
    price: 35000,
    originalPrice: 49000,
    description: 'Bên trong là 1 món bánh ngọt ngẫu nhiên bất ngờ từ thực đơn Cookie & Donut tươi nướng mỗi ngày.',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=450',
    color: 'from-[#FBCFE8] to-[#F472B6]', 
    shadowColor: 'rgba(244,114,182,0.2)',
    textColor: 'text-pink-600',
    bgBadge: 'bg-pink-50 text-pink-700 border-pink-100',
    options: {
      ribbons: ['Ruy-băng hồng ngọt', 'Dây gai thô mộc'],
      greetings: ['Chúc ngày mới ngọt ngào!', 'Cảm ơn đã ghé thăm SaviBite', 'Không lấy thiệp'],
    },
    rating: 4.8,
    salesCount: 312,
  },
  {
    id: 'mb_59',
    name: 'Mystery Box',
    badge: 'Deluxe Cake Box',
    price: 59000,
    originalPrice: 79000,
    description: 'Chứa ngẫu nhiên 1 hũ Tiramisu Klasik Ý hảo hạng, Mousse Matcha Sữa Ong Chúa thơm mịn hoặc Cupcake tinh xảo.',
    image: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&q=80&w=450',
    color: 'from-[#FED7AA] to-[#F97316]', 
    shadowColor: 'rgba(249,115,22,0.2)',
    textColor: 'text-amber-600',
    bgBadge: 'bg-amber-50 text-amber-700 border-amber-100',
    options: {
      ribbons: ['Ruy-băng cam ấm', 'Ruy-băng lụa vàng'],
      greetings: ['Chúc bạn ngon miệng!', 'Happy Birthday To You', 'Gửi lời thương yêu', 'Không lấy thiệp'],
    },
    rating: 4.9,
    salesCount: 428,
  },
  {
    id: 'mb_99',
    name: 'Mystery Box',
    badge: 'Combo Sweet & Sip',
    price: 99000,
    originalPrice: 135000,
    description: 'Bột bánh và trà thơm sánh đôi! Nhận ngẫu nhiên 1 phần nước uống mát lạnh mát lòng và 1 chiếc Croissant bơ Pháp ngàn lớp thơm phức.',
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=450',
    color: 'from-[#CCFBF1] to-[#0D9488]', 
    shadowColor: 'rgba(13,148,136,0.2)',
    textColor: 'text-teal-600',
    bgBadge: 'bg-teal-50 text-teal-700 border-teal-100',
    options: {
      ribbons: ['Ruy-băng lụa Teal', 'Dây gai mộc mạc'],
      greetings: ['Thưởng trà bánh thật chill nhé!', 'Chúc ngày làm việc năng lượng', 'Không lấy thiệp'],
    },
    rating: 4.9,
    salesCount: 215,
  },
  {
    id: 'mb_149',
    name: 'Mystery Box',
    badge: 'Supreme Gold Box',
    price: 149000,
    originalPrice: 220000,
    description: 'Hộp siêu quà vương giả mộc mạc! Chứa 1 ổ bánh kem dâu tây Hokkaido size M tươi mới hoàn sau ngẫu nhiên để ăn mừng.',
    image: 'https://images.unsplash.com/photo-1577174828131-d8ec22f6087b?auto=format&fit=crop&q=80&w=450',
    color: 'from-[#FEF08A] to-[#EAB308]', 
    shadowColor: 'rgba(234,179,8,0.2)',
    textColor: 'text-amber-800',
    bgBadge: 'bg-yellow-50 text-yellow-800 border-yellow-105',
    options: {
      ribbons: ['Ruy-băng thắt nơ Gold', 'Ruy-băng lụa đỏ'],
      greetings: ['Chúc mừng buổi tiệc tuyệt vời!', 'Cảm ơn vì tất cả!', 'Không lấy thiệp'],
    },
    rating: 5.0,
    salesCount: 189,
  }
];
