import { Product, Notification, UserProfile, Restaurant } from './types';

export const CATEGORIES = [
  { id: 'all', label: 'Tất cả', icon: 'Sparkles' },
  { id: 'cake', label: 'Bánh Ngọt', icon: 'Cake' },
  { id: 'savory', label: 'Bánh Mặn', icon: 'Croissant' },
  { id: 'cookie', label: 'Cookie & Tart', icon: 'Cookie' },
  { id: 'drinks', label: 'Thức Uống', icon: 'Coffee' },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'res_01',
    name: 'SaviBite Bakery',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    distance: 1.2,
    tags: ['Bánh kem', 'Croissant'],
    promoBadge: 'Giảm 20k'
  },
  {
    id: 'res_02',
    name: 'The Dreamers Dessert',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=400',
    rating: 4.8,
    distance: 3.5,
    tags: ['Tiramisu', 'Mousse'],
    promoBadge: 'Freeship'
  },
  {
    id: 'res_03',
    name: 'Katinat Saigon Kafe',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    distance: 0.8,
    tags: ['Trà sữa', 'Cà phê', 'Hot'],
    promoBadge: 'Mã 15%'
  },
  {
    id: 'res_04',
    name: 'Bơ & Bột Patisserie',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400',
    rating: 4.7,
    distance: 2.1,
    tags: ['Bánh mặn', 'Donut'],
  },
  {
    id: 'res_05',
    name: 'Tous Les Jours',
    image: 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    distance: 1.5,
    tags: ['Bánh mì', 'Bánh kem'],
    promoBadge: 'Freeship'
  },
  {
    id: 'res_06',
    name: 'Paris Baguette',
    image: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&q=80&w=400',
    rating: 4.6,
    distance: 4.2,
    tags: ['Bánh ngọt', 'Ăn nhẹ'],
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'sb_01',
    restaurantId: 'res_01',
    name: 'Bánh Kem Dâu Tây Savi',
    price: 65000,
    originalPrice: 75000,
    description: 'Bánh gato cốt dâu tây mềm ẩm ngọt mát kết hợp lớp kem sữa tươi Hokkaido.',
    category: 'cake',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    salesCount: 1230,
    sizes: ['S (Slice)', 'M (Ổ nhỏ)', 'L (Ổ lớn)'],
    options: ['100% Ngọt', '70% Ngọt', '50% Ngọt'],
    hotDeals: true,
  },
  {
    id: 'sb_02',
    restaurantId: 'res_04',
    name: 'Bánh Mì Chà Bông Phô Mai',
    price: 35000,
    description: 'Bánh mì mặn với chà bông heo và nhân phô mai tan chảy thơm lừng.',
    category: 'savory',
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&q=80&w=400',
    rating: 4.7,
    salesCount: 885,
    sizes: ['Bình thường', 'Thêm phô mai'],
    options: ['Không hành', 'Thêm sốt cay'],
    hotDeals: false,
  },
  {
    id: 'sb_03',
    restaurantId: 'res_02',
    name: 'Tiramisu Klasik Ý',
    price: 55000,
    originalPrice: 65000,
    description: 'Bánh Tiramisu truyền thống Ý với cốt bánh thấm đượm espresso đậm đà cùng phô mai Mascarpone.',
    category: 'cake',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&q=80&w=400',
    rating: 4.8,
    salesCount: 910,
    sizes: ['S (Slice)', 'M (Hũ gỗ)'],
    options: ['Tiêu chuẩn', 'Ít ngọt'],
    hotDeals: true,
  },
  {
    id: 'sb_04',
    restaurantId: 'res_01',
    name: 'Bánh Croissant Bơ Pháp',
    price: 35000,
    description: 'Bánh mì sừng bò bơ Pháp ngàn lớp giòn rụm bên ngoài, dậy hương bơ thơm lừng.',
    category: 'savory',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=400',
    rating: 4.6,
    salesCount: 445,
    sizes: ['Standard Size'],
    options: ['Làm nóng', 'Không làm nóng'],
    hotDeals: false,
  },
  {
    id: 'sb_09',
    restaurantId: 'res_03',
    name: 'Trà Sữa Thái Đỏ',
    price: 35000,
    description: 'Trà sữa Thái đỏ thơm béo, đậm vị trà.',
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    salesCount: 2420,
    sizes: ['Size M', 'Size L'],
    options: ['50% Đá, 50% Đường', '100% Đá, Đường Chuẩn', 'Thêm trân châu đen (+10k)'],
    hotDeals: true,
  },
  {
    id: 'sb_10',
    restaurantId: 'res_03',
    name: 'Cà Phê Sữa Đá',
    price: 29000,
    description: 'Cà phê rang xay nguyên chất pha phin đậm đà.',
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=400',
    rating: 4.7,
    salesCount: 1290,
    sizes: ['Size M', 'Size L'],
    options: ['Ít ngọt', 'Bình thường'],
    hotDeals: false,
  },
  {
    id: 'sb_11',
    restaurantId: 'res_04',
    name: 'Bánh Tart Trứng Bồ Đào Nha',
    price: 25000,
    description: 'Vỏ tart giòn rụm ngàn lớp với nhân kem trứng nướng cháy xém béo ngậy.',
    category: 'cookie',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=400',
    rating: 4.8,
    salesCount: 3190,
    sizes: ['1 Chiếc', 'Hộp 4 chiếc'],
    options: ['Làm nóng', 'Không làm nóng'],
    hotDeals: true,
  },
  {
    id: 'sb_12',
    restaurantId: 'res_02',
    name: 'Macaron Hộp 6 Cái',
    price: 150000,
    originalPrice: 180000,
    description: 'Hộp 6 chiếc macaron nhiều hương vị: dâu, chanh dây, chocolate, matcha, vanilla.',
    category: 'cookie',
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&q=80&w=400',
    rating: 4.9,
    salesCount: 1540,
    sizes: ['Hộp 6 cái', 'Hộp 12 cái'],
    options: ['Kèm thiệp', 'Không thiệp'],
    hotDeals: true,
  },
  {
    id: 'sb_13',
    restaurantId: 'res_05',
    name: 'Bánh Mì Bơ Tỏi Phô Mai',
    price: 45000,
    description: 'Bánh mì bơ tỏi nướng giòn với nhân phô mai kem kéo sợi Hàn Quốc béo ngậy.',
    category: 'savory',
    image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?auto=format&fit=crop&q=80&w=400',
    rating: 4.8,
    salesCount: 2200,
    sizes: ['Bình thường', 'Thêm phô mai'],
    options: ['Làm nóng', 'Không làm nóng'],
    hotDeals: false,
  },
  {
    id: 'sb_14',
    restaurantId: 'res_03',
    name: 'Trà Đào Cam Sả',
    price: 45000,
    description: 'Trà đào thanh mát kết hợp với hương cam vàng sả thơm lừng giải nhiệt.',
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=400',
    rating: 4.7,
    salesCount: 4500,
    sizes: ['M (Tiêu chuẩn)', 'L (Lớn)'],
    options: ['100% Đá', '50% Đá', 'Không Đá'],
    hotDeals: false,
  },
  {
    id: 'sb_15',
    restaurantId: 'res_06',
    name: 'Mousse Trà Xanh Matcha',
    price: 60000,
    originalPrice: 70000,
    description: 'Bánh mousse mềm tan với hương vị matcha Nhật Bản đậm đà không quá ngọt.',
    category: 'cake',
    image: 'https://images.unsplash.com/photo-1481391319762-47dcf7295cb1?auto=format&fit=crop&q=80&w=400',
    rating: 4.6,
    salesCount: 890,
    sizes: ['S (Slice)'],
    options: ['Nhiều bột trà', 'Ít bột trà'],
    hotDeals: true,
  },
  {
    id: 'sb_16',
    restaurantId: 'res_04',
    name: 'Donut Phủ Sô Cô La Hạt Dẻ',
    price: 30000,
    description: 'Bánh donut chiên phồng xốp phủ chocolate bỉ và hạt dẻ cười đập vụn giòn tan.',
    category: 'cookie',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=400',
    rating: 4.5,
    salesCount: 1120,
    sizes: ['1 Chiếc', 'Hộp 3 chiếc'],
    options: ['Nhiều hạt', 'Bình thường'],
    hotDeals: false,
  }
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'not_01',
    title: '🎁 Quà Tặng Lần Đầu Đến SaviBite Bakery!',
    content: 'Tặng bạn mã ưu đãi giảm ngay 30k cho đơn hàng đầu tiên. Nhập mã: NEWBIE30!',
    time: 'Vừa xong',
    read: false,
    type: 'promo',
  },
  {
    id: 'not_02',
    title: '✅ Đơn hàng đã sẵn sàng',
    content: 'Đơn hàng của bạn đã chuẩn bị xong. Vui lòng đến nhận tại cửa hàng.',
    time: '2 phút trước',
    read: false,
    type: 'order',
  }
];

export const INITIAL_USER: UserProfile = {
  name: "Duy Nguyễn",
  phone: "0987 *** 321",
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=200",
  tier: "Gold",
  points: 1520,
  savedVouchers: ['NEWBIE30', 'FREESHIP15', 'GIAM50K']
};

export const PROMO_VOUCHERS = [
  { code: 'NEWBIE30', description: 'Giảm 30.000đ cho đơn hàng đầu', discountValue: 30000, minOrder: 50000 },
  { code: 'FREESHIP15', description: 'Giảm 15k phí vận chuyển', discountValue: 15000, minOrder: 40000 },
  { code: 'GIAM50K', description: 'Giảm thẳng 50.000đ cho hóa đơn từ 200k', discountValue: 50000, minOrder: 200000 }
];
